"""empty message

Revision ID: 060044f56965
Revises: de581fb34e53
Create Date: 2023-04-29 18:25:01.936915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '060044f56965'
down_revision = 'de581fb34e53'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Authors', sa.Column('createdAt', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('Authors', sa.Column('updatedAt', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Authors', 'updatedAt')
    op.drop_column('Authors', 'createdAt')
    # ### end Alembic commands ###
