"""empty message

Revision ID: 0a30f15f1bcf
Revises: 99f9fe3f757e
Create Date: 2023-04-29 17:48:23.987785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a30f15f1bcf'
down_revision = '99f9fe3f757e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
