"""empty message

Revision ID: 102a3931f28b
Revises: d52dbff52b2e
Create Date: 2023-05-05 07:41:26.024466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '102a3931f28b'
down_revision = 'd52dbff52b2e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
