"""empty message

Revision ID: 12392298860f
Revises: c30f0a661316
Create Date: 2023-04-29 18:29:46.619015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12392298860f'
down_revision = 'c30f0a661316'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Authors', sa.Column('createdAt', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.add_column('Authors', sa.Column('updatedAt', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Authors', 'updatedAt')
    op.drop_column('Authors', 'createdAt')
    # ### end Alembic commands ###
