"""empty message

Revision ID: 13e5b4fc4e6a
Revises: 7fa7cd5f7cb7
Create Date: 2023-05-06 11:07:03.142494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13e5b4fc4e6a'
down_revision = '7fa7cd5f7cb7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('name', sa.String(), nullable=True))
    op.add_column('User', sa.Column('surname', sa.String(), nullable=True))
    op.add_column('User', sa.Column('email', sa.String(), nullable=True))
    op.add_column('User', sa.Column('birth_date', sa.Date(), nullable=True))
    op.add_column('User', sa.Column('personal_identificatior', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'personal_identificatior')
    op.drop_column('User', 'birth_date')
    op.drop_column('User', 'email')
    op.drop_column('User', 'surname')
    op.drop_column('User', 'name')
    # ### end Alembic commands ###
