"""empty message

Revision ID: 1eef41db477e
Revises: 8c84157b0406
Create Date: 2023-05-07 11:45:21.101477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1eef41db477e'
down_revision = '8c84157b0406'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
