"""empty message

Revision ID: 299d1305c41b
Revises: f217648d6619
Create Date: 2023-05-07 11:05:30.008023

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '299d1305c41b'
down_revision = 'f217648d6619'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
