"""empty message

Revision ID: 31d1cbf120f4
Revises: 78a46f7dfe21
Create Date: 2023-05-06 16:19:41.230674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31d1cbf120f4'
down_revision = '78a46f7dfe21'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
