"""empty message

Revision ID: 42a9cca57b8f
Revises: 102a3931f28b
Create Date: 2023-05-06 08:19:37.561651

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '42a9cca57b8f'
down_revision = '102a3931f28b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Authors', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('Authors', sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_column('Authors', 'createdAt')
    op.drop_column('Authors', 'updatedAt')
    op.add_column('Category', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('Category', sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_column('Category', 'createdAt')
    op.drop_column('Category', 'updatedAt')
    op.add_column('Publication', sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.add_column('Publication', sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.drop_column('Publication', 'createdAt')
    op.drop_column('Publication', 'updatedAt')
    op.drop_constraint('publication_authors_author_id_fkey', 'publication_authors', type_='foreignkey')
    op.drop_constraint('publication_authors_publication_id_fkey', 'publication_authors', type_='foreignkey')
    op.create_foreign_key(None, 'publication_authors', 'Authors', ['author_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'publication_authors', 'Publication', ['publication_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('publication_categories_category_id_fkey', 'publication_categories', type_='foreignkey')
    op.drop_constraint('publication_categories_publication_id_fkey', 'publication_categories', type_='foreignkey')
    op.create_foreign_key(None, 'publication_categories', 'Category', ['category_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'publication_categories', 'Publication', ['publication_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'publication_categories', type_='foreignkey')
    op.drop_constraint(None, 'publication_categories', type_='foreignkey')
    op.create_foreign_key('publication_categories_publication_id_fkey', 'publication_categories', 'Publication', ['publication_id'], ['id'])
    op.create_foreign_key('publication_categories_category_id_fkey', 'publication_categories', 'Category', ['category_id'], ['id'])
    op.drop_constraint(None, 'publication_authors', type_='foreignkey')
    op.drop_constraint(None, 'publication_authors', type_='foreignkey')
    op.create_foreign_key('publication_authors_publication_id_fkey', 'publication_authors', 'Publication', ['publication_id'], ['id'])
    op.create_foreign_key('publication_authors_author_id_fkey', 'publication_authors', 'Authors', ['author_id'], ['id'])
    op.add_column('Publication', sa.Column('updatedAt', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('Publication', sa.Column('createdAt', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_column('Publication', 'updated_at')
    op.drop_column('Publication', 'created_at')
    op.add_column('Category', sa.Column('updatedAt', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('Category', sa.Column('createdAt', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_column('Category', 'updated_at')
    op.drop_column('Category', 'created_at')
    op.add_column('Authors', sa.Column('updatedAt', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('Authors', sa.Column('createdAt', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_column('Authors', 'updated_at')
    op.drop_column('Authors', 'created_at')
    # ### end Alembic commands ###
