"""empty message

Revision ID: 4432b3083a1f
Revises: b975e3f80371
Create Date: 2023-04-29 17:41:16.146690

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4432b3083a1f'
down_revision = 'b975e3f80371'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
