"""empty message

Revision ID: 51d6036a91d5
Revises: 6678e14e78c9
Create Date: 2023-05-06 17:07:02.334205

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51d6036a91d5'
down_revision = '6678e14e78c9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instance', sa.Column('type', sa.Enum('physical', 'ebook', 'audiobook', name='type_enum'), nullable=True))
    op.add_column('instance', sa.Column('status', sa.Enum('available', 'reserved', name='status_enum'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instance', 'status')
    op.drop_column('instance', 'type')
    # ### end Alembic commands ###
