"""empty message

Revision ID: 59b9a44b1187
Revises: ec23cfb5a36a
Create Date: 2023-04-29 17:55:18.814371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59b9a44b1187'
down_revision = 'ec23cfb5a36a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
