"""empty message

Revision ID: 5cbc8d92c079
Revises: 7a1133f419e3
Create Date: 2023-04-29 17:39:31.620300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5cbc8d92c079'
down_revision = '7a1133f419e3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
