"""empty message

Revision ID: 6678e14e78c9
Revises: 993116eea7d4
Create Date: 2023-05-06 17:06:45.984437

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6678e14e78c9'
down_revision = '993116eea7d4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instance', 'status')
    op.drop_column('instance', 'type')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instance', sa.Column('type', postgresql.ENUM('physical', 'ebook', 'audiobook', name='type_enum'), autoincrement=False, nullable=True))
    op.add_column('instance', sa.Column('status', postgresql.ENUM('active', 'inactive', 'expired', name='status_enum'), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
