"""empty message

Revision ID: 683131723b4d
Revises: b16d0ddeb7e5
Create Date: 2023-04-29 17:59:13.451633

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '683131723b4d'
down_revision = 'b16d0ddeb7e5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Authors', 'updatedAt')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Authors', sa.Column('updatedAt', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
