"""empty message

Revision ID: 78a46f7dfe21
Revises: ec889e5a6afc
Create Date: 2023-05-06 16:06:29.885812

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78a46f7dfe21'
down_revision = 'ec889e5a6afc'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
