"""empty message

Revision ID: 7a1133f419e3
Revises: b142cfac8afd
Create Date: 2023-04-29 17:38:10.226201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a1133f419e3'
down_revision = 'b142cfac8afd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
