"""empty message

Revision ID: 7fa7cd5f7cb7
Revises: d478ffdce235
Create Date: 2023-05-06 11:02:15.350811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7fa7cd5f7cb7'
down_revision = 'd478ffdce235'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
