"""empty message

Revision ID: 823a40a86594
Revises: a96a75f52273
Create Date: 2023-04-29 16:24:50.699648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '823a40a86594'
down_revision = 'a96a75f52273'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
