"""empty message

Revision ID: 993116eea7d4
Revises: 31d1cbf120f4
Create Date: 2023-05-06 16:57:46.272422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '993116eea7d4'
down_revision = '31d1cbf120f4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
