"""empty message

Revision ID: a7702a953399
Revises: b58d75a4d26a
Create Date: 2023-05-06 11:26:13.053317

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7702a953399'
down_revision = 'b58d75a4d26a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
