"""empty message

Revision ID: b142cfac8afd
Revises: 823a40a86594
Create Date: 2023-04-29 17:37:21.766407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b142cfac8afd'
down_revision = '823a40a86594'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
