"""empty message

Revision ID: b16d0ddeb7e5
Revises: 59b9a44b1187
Create Date: 2023-04-29 17:55:54.623866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b16d0ddeb7e5'
down_revision = '59b9a44b1187'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
