"""empty message

Revision ID: b1d67fc76099
Revises: 42a9cca57b8f
Create Date: 2023-05-06 10:39:50.305378

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1d67fc76099'
down_revision = '42a9cca57b8f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
