"""empty message

Revision ID: b2744bbd5737
Revises: 6afd9299a83d
Create Date: 2023-05-06 17:42:15.212166

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2744bbd5737'
down_revision = '6afd9299a83d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Card', sa.Column('status', sa.Enum('active', 'inactive', 'expired', name='status_enum'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Card', 'status')
    # ### end Alembic commands ###
