"""empty message

Revision ID: b58d75a4d26a
Revises: 13e5b4fc4e6a
Create Date: 2023-05-06 11:15:00.741108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b58d75a4d26a'
down_revision = '13e5b4fc4e6a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('personal_identificator', sa.String(), nullable=True))
    op.drop_column('User', 'personal_identificatior')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('personal_identificatior', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('User', 'personal_identificator')
    # ### end Alembic commands ###
