"""empty message

Revision ID: b975e3f80371
Revises: 5cbc8d92c079
Create Date: 2023-04-29 17:40:27.645794

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b975e3f80371'
down_revision = '5cbc8d92c079'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
