"""empty message

Revision ID: c039cbfc6f7c
Revises: 51d6036a91d5
Create Date: 2023-05-06 17:19:29.432405

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c039cbfc6f7c'
down_revision = '51d6036a91d5'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
