"""empty message

Revision ID: cbdb0e6ee674
Revises: 163d05d1272d
Create Date: 2023-05-06 15:17:52.620119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbdb0e6ee674'
down_revision = '163d05d1272d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
