"""empty message

Revision ID: d52dbff52b2e
Revises: 7966436a3672
Create Date: 2023-05-05 07:39:47.636312

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd52dbff52b2e'
down_revision = '7966436a3672'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
