"""empty message

Revision ID: ec23cfb5a36a
Revises: 0a30f15f1bcf
Create Date: 2023-04-29 17:53:20.560315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec23cfb5a36a'
down_revision = '0a30f15f1bcf'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
