"""empty message

Revision ID: ec889e5a6afc
Revises: cbdb0e6ee674
Create Date: 2023-05-06 15:21:02.741131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ec889e5a6afc'
down_revision = 'cbdb0e6ee674'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
