"""empty message

Revision ID: f217648d6619
Revises: 35877c2294d9
Create Date: 2023-05-07 09:16:15.509561

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f217648d6619'
down_revision = '35877c2294d9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('instance')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instance',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('publisher', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('year', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('publication_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('type', postgresql.ENUM('physical', 'ebook', 'audiobook', name='type_enum'), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('available', 'reserved', name='statusInstance_enum'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['publication_id'], ['Publication.id'], name='instance_publication_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='instance_pkey')
    )
    # ### end Alembic commands ###
